# All configuration options

[mqtt]
base_topic = "daikin2mqtt"          # Required: MQTT base topic
broker = "localhost"                # Required: MQTT broker
port = 1883                         # Required: MQTT port
# user = "my_user"                  # Optional: MQTT broker user (default: nothing)
# password = "my_password"          # Optional: MQTT broker password (default: nothing)

[daikin]
discovery_timeout = 5               # Required: Seconds to wait for units to respond
rediscovery_minutes = 20            # Required: Minutes between unit discovery attempts
update_period = 60                  # Required: Seconds pause (s) between fetching updates from inverters

[[inverter]]
  mac = "C0E434E69F27"              # Required: The unpunctuated MAC address of the unit
  friendly_name = "Steve_Office"    # Required: Will form part of the MQTT topic
  
[[inverter]]
  mac = "C0E434E60BC6"             
  friendly_name = "Spare_Bedroom"   

[[inverter]]
  mac = "D8C0A664E830"             
  friendly_name = "Music_Room"   
  