# All configuration options
# All entries are required 

[mqtt]
base_topic = "daikin2mqtt"          # MQTT base topic
broker = "localhost"                # MQTT broker
port = 1883                         # MQTT port
username = ""                       # MQTT broker user (use "" for none)
password = ""                       # MQTT broker password (use "" for none)

[daikin]
update_period = 60                  # Seconds pause (s) between regular updates from inverters

[[inverter]]
  ip_addr = "192.168.1.50"          # the IP address of the unit's adaptor
  friendly_name = "Steve_Office"    # Will form part of the MQTT topic
  
[[inverter]]
  ip_addr = "192.168.1.53"
  friendly_name = "Spare_Bedroom"   

  